project: 
  type: website
  output-dir: docs
  
website: 
  title: "Hiba Awan"
  navbar: 
   left: 
     - index.qmd
     - about.qmd
     - midproj.qmd
     - midprojcode.qmd
     - finalproj.qmd
     - finalprojcode.qmd

